### PR TITLE
Add file handling utility for template

### PR DESCRIPTION
**Pull request by brianmcgillion**

### CODE REVIEW

**Comment by myshevchuk** [comment]
Thank you very much for you work, which is the first pull request in this repository!

**Comment by brianmcgillion** [comment]
NP. Thank you all, this is a really great tool!

**Comment by Zaeph** [comment]
> NP. Thank you all, this is a really great tool!

Thanks a bunch for your PR, and I'm glad you're liking the package! 😸

I went ahead and pushes a couple of changes to your docstrings to make them coherent with the others.  I'm working on a small improvement to be intelligent with the completions.  The idea is the following:
- If you have 2 files with the same name but different extensions, it only show you the extension to choose.
- If you have 2 files with different names and different extensions, it shows you the name of the files and their extensions *without* the path.
- Else, show the entire path.

It should be done Soon™.

**Comment by Zaeph** [comment]
Thank you for your PR! 🎉

I'll make a new PR for the feature I've mentioned above before it has gotten significantly large.

**Pull request merged**
